# name: Build and Analyze
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   build-and-test:
#     name: Build and Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build

#       # - name: Run tests with coverage
#       #   run: yarn test --coverage

#       # - name: Upload coverage reports to Codecov
#       #   uses: codecov/codecov-action@v3
#       #   env:
#       #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#   sonarcloud:
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     needs: build-and-test
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       # - name: Set up Node.js
#       #   uses: actions/setup-node@v1
#       #   with:
#       #     node-version: '20'
#       # - name: Install dependencies
#       #   run: npm install
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.organization=rahulb15
#             -Dsonar.projectKey=rahulb15_k-frontend

#   docker:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     needs: [build-and-test, sonarcloud]
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kryptomerch:latest
#           build-args: |
#             NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
#             NEXT_PUBLIC_RELAY_URL=${{ secrets.NEXT_PUBLIC_RELAY_URL }}
#             NEXT_PUBLIC_KDA_NETWORK_TYPE=${{ secrets.NEXT_PUBLIC_KDA_NETWORK_TYPE }}
#             NEXT_PUBLIC_KDA_CHAIN_ID=${{ secrets.NEXT_PUBLIC_KDA_CHAIN_ID }}
#             NEXT_PUBLIC_KDA_GAS_PRICE=${{ secrets.NEXT_PUBLIC_KDA_GAS_PRICE }}
#             NEXT_PUBLIC_KDA_GAS_LIMIT=${{ secrets.NEXT_PUBLIC_KDA_GAS_LIMIT }}
#             NEXT_PUBLIC_KDA_PRECISION=${{ secrets.NEXT_PUBLIC_KDA_PRECISION }}
#             NEXT_PUBLIC_KDA_NETWORK_ID=${{ secrets.NEXT_PUBLIC_KDA_NETWORK_ID }}
#             NEXT_PUBLIC_KDA_FEE=${{ secrets.NEXT_PUBLIC_KDA_FEE }}
#             NEXT_PUBLIC_APR_FEE=${{ secrets.NEXT_PUBLIC_APR_FEE }}
#             NEXT_PUBLIC_KDA_NETWORK=${{ secrets.NEXT_PUBLIC_KDA_NETWORK }}
#             NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
#             NEXT_PUBLIC_ZELCORE_URL=${{ secrets.NEXT_PUBLIC_ZELCORE_URL }}
#             NEXT_PUBLIC_ADMIN_ADDRESS=${{ secrets.NEXT_PUBLIC_ADMIN_ADDRESS }}
#             NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
#             NEXT_PUBLIC_STRIPE_SECRET_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY }}
#             NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
#             NEXT_PUBLIC_LAUNCHPAD_CHARGES=${{ secrets.NEXT_PUBLIC_LAUNCHPAD_CHARGES }}
#             NEXT_PUBLIC_DEFAULT_INSTANCE=${{ secrets.NEXT_PUBLIC_DEFAULT_INSTANCE }}

name: Build and Analyze
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            # - name: Run tests with coverage
            #   run: yarn test --coverage

            # - name: Upload coverage reports to Codecov
            #   uses: codecov/codecov-action@v3
            #   env:
            #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.organization=rahulb15
                      -Dsonar.projectKey=rahulb15_kryptomerch-frontend-testnet

    docker:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: [build-and-test, sonarcloud]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/kryptomerch-frontend-testnet:latest
                  build-args: |
                      NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
                      NEXT_PUBLIC_RELAY_URL=${{ secrets.NEXT_PUBLIC_RELAY_URL }}
                      NEXT_PUBLIC_KDA_NETWORK_TYPE=${{ secrets.NEXT_PUBLIC_KDA_NETWORK_TYPE }}
                      NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
                      NEXT_PUBLIC_ZELCORE_URL=${{ secrets.NEXT_PUBLIC_ZELCORE_URL }}
                      NEXT_PUBLIC_ADMIN_ADDRESS=${{ secrets.NEXT_PUBLIC_ADMIN_ADDRESS }}
                      NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
                      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
                      NEXT_PUBLIC_LAUNCHPAD_CHARGES=${{ secrets.NEXT_PUBLIC_LAUNCHPAD_CHARGES }}
                      NEXT_PUBLIC_WALLETCONNECT_BRIDGE_URL=${{ secrets.NEXT_PUBLIC_WALLETCONNECT_BRIDGE_URL }}
                      NEXT_PUBLIC_WALLETCONNECT_CHAIN_ID=${{ secrets.NEXT_PUBLIC_WALLETCONNECT_CHAIN_ID }}
                      NEXT_PUBLIC_TESTNET_CHAIN_ID=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_ID }}
                      NEXT_PUBLIC_TESTNET_CHAIN_NAME=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_NAME }}
                      NEXT_PUBLIC_TESTNET_CHAIN_NETWORK_ID=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_NETWORK_ID }}
                      NEXT_PUBLIC_TESTNET_CHAIN_NETWORK=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_NETWORK }}
                      NEXT_PUBLIC_TESTNET_CHAIN_GAS_PRICE=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_GAS_PRICE }}
                      NEXT_PUBLIC_TESTNET_CHAIN_GAS_LIMIT=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_GAS_LIMIT }}
                      NEXT_PUBLIC_TESTNET_CHAIN_FEE=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_FEE }}
                      NEXT_PUBLIC_TESTNET_CHAIN_PRECISION=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_PRECISION }}
                      NEXT_PUBLIC_TESTNET_CHAIN_APR_FEE=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_APR_FEE }}
                      NEXT_PUBLIC_TESTNET_CHAIN_VERSION=${{ secrets.NEXT_PUBLIC_TESTNET_CHAIN_VERSION }}
                      NEXT_PUBLIC_TESTNET_DEFAULT_INSTANCE=${{ secrets.NEXT_PUBLIC_TESTNET_DEFAULT_INSTANCE }}
                      NEXT_PUBLIC_TESTNET_WALLETCONNECT_CHAIN_ID=${{ secrets.NEXT_PUBLIC_TESTNET_WALLETCONNECT_CHAIN_ID }}
                      NEXT_PUBLIC_MAINNET_CHAIN_ID=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_ID }}
                      NEXT_PUBLIC_MAINNET_CHAIN_NAME=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_NAME }}
                      NEXT_PUBLIC_MAINNET_CHAIN_NETWORK_ID=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_NETWORK_ID }}
                      NEXT_PUBLIC_MAINNET_CHAIN_NETWORK=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_NETWORK }}
                      NEXT_PUBLIC_MAINNET_CHAIN_GAS_PRICE=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_GAS_PRICE }}
                      NEXT_PUBLIC_MAINNET_CHAIN_GAS_LIMIT=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_GAS_LIMIT }}
                      NEXT_PUBLIC_MAINNET_CHAIN_FEE=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_FEE }}
                      NEXT_PUBLIC_MAINNET_CHAIN_PRECISION=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_PRECISION }}
                      NEXT_PUBLIC_MAINNET_CHAIN_APR_FEE=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_APR_FEE }}
                      NEXT_PUBLIC_MAINNET_CHAIN_VERSION=${{ secrets.NEXT_PUBLIC_MAINNET_CHAIN_VERSION }}
                      NEXT_PUBLIC_MAINNET_DEFAULT_INSTANCE=${{ secrets.NEXT_PUBLIC_MAINNET_DEFAULT_INSTANCE }}
                      NEXT_PUBLIC_MAINNET_WALLETCONNECT_CHAIN_ID=${{ secrets.NEXT_PUBLIC_MAINNET_WALLETCONNECT_CHAIN_ID }}
                      NEXT_PUBLIC_VERSION=${{ secrets.NEXT_PUBLIC_VERSION }}
